'use client';
import { NotificationCenter } from "@/components/NotificatonCenter";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import { Bell, Calendar } from "lucide-react";
import { useState } from "react";

const mockShipments = [
  {
    id: '1',
    supplierName: 'Global Electronics Co.',
    poNumber: 'PO-2025-001',
    port: 'Shanghai Port',
    dateClear: '2025-07-08',
    type: 'Air',
    poType: 'Single',
    term: 'FOB',
    permitStatus: true,
    blAwbNumber: 'AWB-789123456',
    qualityContainer: 'QC-A001',
    taxStatus: true,
    etd: '2025-07-05',
    eta: '2025-07-07',
    status: 'in-transit',
    progress: 60,
    pstStatus: 'completed', // completed, in-progress, not-started
    supplierContact: '+86-21-6234-5678',
    supplierEmail: 'orders@globalelectronics.cn',
    supplierAddress: '123 Industrial Road, Shanghai, China',
    totalValue: 145000,
    weight: '2,450 kg',
    dimensions: '120x80x60 cm',
    assignedAgent: 'Sarah Chen',
    agentContact: '+1-555-0123',
    trackingNumber: 'GE789123456',
    customsDeclaration: 'CD-2025-0078',
    insurance: true,
    priority: 'High',
    specialInstructions: 'Temperature sensitive - keep below 25°C',
    documents: [
      'Commercial Invoice',
      'Packing List',
      'Certificate of Origin',
      'Air Waybill',
      'Export License',
      'Dangerous Goods Declaration',
      'Insurance Certificate',
      'Customs Declaration Form',
      'Quality Control Certificate',
      'Product Specification Sheet'
    ],
    relatedPOs: []
  },
  {
    id: '2',
    supplierName: 'Pacific Manufacturing',
    poNumber: 'PO-2025-002',
    port: 'Los Angeles Port',
    dateClear: '2025-07-10',
    type: 'Oversea',
    poType: 'Co-load',
    term: 'CIF',
    permitStatus: true,
    blAwbNumber: 'BL-456789123',
    qualityContainer: 'CONT-789456',
    taxStatus: false,
    etd: '2025-06-25',
    eta: '2025-07-08',
    status: 'clearance',
    progress: 85,
    pstStatus: 'completed',
    supplierContact: '+1-310-555-9876',
    supplierEmail: 'shipping@pacificmfg.com',
    supplierAddress: '456 Harbor Blvd, Los Angeles, CA 90210',
    totalValue: 89500,
    weight: '15,200 kg',
    dimensions: '40ft Container',
    assignedAgent: 'Mike Rodriguez',
    agentContact: '+1-555-0456',
    trackingNumber: 'PM456789123',
    customsDeclaration: 'CD-2025-0089',
    insurance: true,
    priority: 'Medium',
    specialInstructions: 'Fragile goods - handle with care',
    documents: [
      'Bill of Lading',
      'Commercial Invoice',
      'Packing List',
      'Insurance Certificate',
      'Container Load Plan',
      'Fumigation Certificate',
      'Export Permit',
      'Customs Bond',
      'Freight Forwarder Receipt',
      'ISF (10+2) Filing'
    ],
    relatedPOs: ['PO-2025-007', 'PO-2025-008']
  },
  {
    id: '3',
    supplierName: 'Regional Suppliers Ltd.',
    poNumber: 'PO-2025-003',
    port: 'Chicago Hub',
    dateClear: '2025-07-06',
    type: 'Truck',
    poType: 'Multiple',
    term: 'DDP',
    permitStatus: true,
    blAwbNumber: 'TR-123456789',
    qualityContainer: 'QC-T003',
    taxStatus: true,
    etd: '2025-07-04',
    eta: '2025-07-05',
    status: 'completed',
    progress: 100,
    pstStatus: 'completed',
    supplierContact: '+1-312-555-7890',
    supplierEmail: 'logistics@regionalsuppliers.com',
    supplierAddress: '789 Logistics Way, Chicago, IL 60601',
    totalValue: 32000,
    weight: '3,800 kg',
    dimensions: 'Standard Truck Load',
    assignedAgent: 'Jennifer Kim',
    agentContact: '+1-555-0789',
    trackingNumber: 'RS123456789',
    customsDeclaration: 'N/A (Domestic)',
    insurance: false,
    priority: 'Low',
    specialInstructions: 'Standard delivery',
    documents: [
      'Delivery Receipt',
      'Commercial Invoice',
      'Packing Slip',
      'Transport Agreement',
      'Driver License Copy',
      'Vehicle Registration',
      'Cargo Insurance'
    ],
    relatedPOs: []
  },
  {
    id: '4',
    supplierName: 'Euro Components AG',
    poNumber: 'PO-2025-004',
    port: 'Hamburg Port',
    dateClear: '2025-07-12',
    type: 'Oversea',
    poType: 'Co-load',
    term: 'FOB',
    permitStatus: false,
    blAwbNumber: 'BL-987654321',
    qualityContainer: 'CONT-456123',
    taxStatus: true,
    etd: '2025-07-02',
    eta: '2025-07-09',
    status: 'delayed',
    progress: 40,
    pstStatus: 'in-progress',
    supplierContact: '+49-40-1234567',
    supplierEmail: 'export@eurocomponents.de',
    supplierAddress: 'Hafenstraße 12, Hamburg, Germany',
    totalValue: 198000,
    weight: '18,900 kg',
    dimensions: '40ft Container',
    assignedAgent: 'David Mueller',
    agentContact: '+1-555-0234',
    trackingNumber: 'EC987654321',
    customsDeclaration: 'CD-2025-0045',
    insurance: true,
    priority: 'High',
    specialInstructions: 'Requires CE certification verification',
    documents: [
      'Bill of Lading',
      'CE Certificate',
      'Commercial Invoice',
      'Packing List',
      'Technical Documentation',
      'Declaration of Conformity',
      'Test Reports',
      'ROHS Compliance Certificate',
      'Export License (EU)',
      'Origin Certificate EUR.1'
    ],
    relatedPOs: ['PO-2025-009', 'PO-2025-010', 'PO-2025-011']
  },
  {
    id: '5',
    supplierName: 'Asia Tech Solutions',
    poNumber: 'PO-2025-005',
    port: 'Hong Kong Airport',
    dateClear: '2025-07-17',
    type: 'Air',
    poType: 'Single',
    term: 'EXW',
    permitStatus: true,
    blAwbNumber: 'AWB-555666777',
    qualityContainer: 'QC-A005',
    taxStatus: true,
    etd: '2025-07-15',
    eta: '2025-07-16',
    status: 'submitted',
    progress: 25,
    pstStatus: 'not-started',
    supplierContact: '+852-2345-6789',
    supplierEmail: 'orders@asiatech.hk',
    supplierAddress: 'Unit 15, Tech Park, Hong Kong',
    totalValue: 76500,
    weight: '1,200 kg',
    dimensions: '100x60x40 cm',
    assignedAgent: 'Lisa Wong',
    agentContact: '+1-555-0567',
    trackingNumber: 'AT555666777',
    customsDeclaration: 'CD-2025-0067',
    insurance: true,
    priority: 'Medium',
    specialInstructions: 'Electronics - anti-static packaging required',
    documents: [
      'Air Waybill',
      'Commercial Invoice',
      'Tech Specifications',
      'Quality Certificate',
      'FCC Certification',
      'Anti-Static Packaging Certificate',
      'Component List',
      'Software License Documentation',
      'Warranty Information'
    ],
    relatedPOs: []
  },
  {
    id: '6',
    supplierName: 'Multi Source Industries',
    poNumber: 'PO-2025-006',
    port: 'Seattle Port',
    dateClear: '2025-07-29',
    type: 'Oversea',
    poType: 'Multiple',
    term: 'FOB',
    permitStatus: true,
    blAwbNumber: 'BL-333444555',
    qualityContainer: 'CONT-123789',
    taxStatus: true,
    etd: '2025-07-19',
    eta: '2025-07-21',
    status: 'confirm',
    progress: 70,
    pstStatus: 'in-progress',
    supplierContact: '+1-206-555-4321',
    supplierEmail: 'shipping@multisource.com',
    supplierAddress: '321 Harbor View, Seattle, WA 98101',
    totalValue: 156000,
    weight: '12,500 kg',
    dimensions: '40ft Container',
    assignedAgent: 'Tom Wilson',
    agentContact: '+1-555-0890',
    trackingNumber: 'MS333444555',
    customsDeclaration: 'CD-2025-0092',
    insurance: true,
    priority: 'Medium',
    specialInstructions: 'Mixed cargo - separate handling required',
    documents: [
      'Bill of Lading',
      'Commercial Invoice',
      'Packing List',
      'Manifest',
      'Consolidation Certificate',
      'Hazardous Materials Declaration',
      'Multiple Supplier Certificates',
      'Weight & Measurement Certificate',
      'Container Inspection Report'
    ],
    relatedPOs: []
  },
  {
    id: '7',
    supplierName: 'Brazilian Coffee Co.',
    poNumber: 'PO-2025-007',
    port: 'Santos Port',
    dateClear: '2025-07-15',
    type: 'Oversea',
    poType: 'Single',
    term: 'CFR',
    permitStatus: true,
    blAwbNumber: 'BL-777888999',
    qualityContainer: 'CONT-567890',
    taxStatus: true,
    etd: '2025-06-28',
    eta: '2025-07-12',
    status: 'approved',
    progress: 55,
    pstStatus: 'completed',
    supplierContact: '+55-13-3456-7890',
    supplierEmail: 'export@braziliancoffee.com.br',
    supplierAddress: 'Rua do Porto 123, Santos, SP, Brazil',
    totalValue: 67800,
    weight: '22,000 kg',
    dimensions: '20ft Container',
    assignedAgent: 'Carlos Silva',
    agentContact: '+1-555-0678',
    trackingNumber: 'BC777888999',
    customsDeclaration: 'CD-2025-0123',
    insurance: true,
    priority: 'Medium',
    specialInstructions: 'Food grade - maintain dry conditions',
    documents: [
      'Bill of Lading',
      'Phytosanitary Certificate',
      'Commercial Invoice',
      'Quality Certificate',
      'Coffee Bean Grading Certificate',
      'Organic Certification',
      'Fair Trade Certificate',
      'Health Certificate',
      'Moisture Content Report',
      'Export Registration Brazil'
    ],
    relatedPOs: []
  },
  {
    id: '8',
    supplierName: 'Nordic Furniture AB',
    poNumber: 'PO-2025-008',
    port: 'Gothenburg Port',
    dateClear: '2025-07-24',
    type: 'Oversea',
    poType: 'Multiple',
    term: 'DDP',
    permitStatus: true,
    blAwbNumber: 'BL-111222333',
    qualityContainer: 'CONT-890123',
    taxStatus: false,
    etd: '2025-07-17',
    eta: '2025-07-21',
    status: 'preparing',
    progress: 88,
    pstStatus: 'in-progress',
    supplierContact: '+46-31-123-4567',
    supplierEmail: 'shipping@nordicfurniture.se',
    supplierAddress: 'Industrigatan 45, Gothenburg, Sweden',
    totalValue: 234000,
    weight: '16,800 kg',
    dimensions: '40ft Container',
    assignedAgent: 'Anna Larsson',
    agentContact: '+1-555-0345',
    trackingNumber: 'NF111222333',
    customsDeclaration: 'CD-2025-0156',
    insurance: true,
    priority: 'Low',
    specialInstructions: 'Wooden furniture - FSC certified',
    documents: [
      'Bill of Lading',
      'FSC Certificate',
      'Commercial Invoice',
      'Packing List',
      'Wood Treatment Certificate',
      'CARB Compliance Certificate',
      'Assembly Instructions',
      'Quality Assurance Report',
      'Sustainable Sourcing Certificate'
    ],
    relatedPOs: []
  },
  {
    id: '9',
    supplierName: 'Indian Textile Mills',
    poNumber: 'PO-2025-009',
    port: 'Mumbai Port',
    dateClear: '2025-07-11',
    type: 'Oversea',
    poType: 'Co-load',
    term: 'FOB',
    permitStatus: true,
    blAwbNumber: 'BL-444555666',
    qualityContainer: 'CONT-234567',
    taxStatus: true,
    etd: '2025-06-30',
    eta: '2025-07-09',
    status: 'completed',
    progress: 100,
    pstStatus: 'completed',
    supplierContact: '+91-22-2345-6789',
    supplierEmail: 'exports@indiantextiles.in',
    supplierAddress: 'Industrial Estate, Mumbai, Maharashtra, India',
    totalValue: 98500,
    weight: '14,200 kg',
    dimensions: '40ft Container',
    assignedAgent: 'Priya Sharma',
    agentContact: '+1-555-0456',
    trackingNumber: 'IT444555666',
    customsDeclaration: 'CD-2025-0134',
    insurance: false,
    priority: 'Medium',
    specialInstructions: 'Textile goods - moisture protection required',
    documents: [
      'Bill of Lading',
      'Commercial Invoice',
      'Packing List',
      'Textile Certificate',
      'OEKO-TEX Certificate',
      'GOTS Certificate',
      'Fabric Content Label',
      'Color Fastness Test Report',
      'Anti-Dumping Certificate',
      'GSP Certificate of Origin'
    ],
    relatedPOs: ['PO-2025-017', 'PO-2025-018']
  },
  {
    id: '10',
    supplierName: 'Canadian Lumber Corp',
    poNumber: 'PO-2025-010',
    port: 'Vancouver Port',
    dateClear: '2025-07-23',
    type: 'Truck',
    poType: 'Single',
    term: 'FOB',
    permitStatus: true,
    blAwbNumber: 'TR-666777888',
    qualityContainer: 'QC-T010',
    taxStatus: true,
    etd: '2025-07-16',
    eta: '2025-07-17',
    status: 'preparing',
    progress: 35,
    pstStatus: 'not-started',
    supplierContact: '+1-604-555-9876',
    supplierEmail: 'logistics@canadianlumber.ca',
    supplierAddress: '789 Forestry Road, Vancouver, BC, Canada',
    totalValue: 87200,
    weight: '28,500 kg',
    dimensions: 'Flatbed Truck Load',
    assignedAgent: 'Robert Johnson',
    agentContact: '+1-555-0789',
    trackingNumber: 'CL666777888',
    customsDeclaration: 'CD-2025-0178',
    insurance: true,
    priority: 'High',
    specialInstructions: 'Hazardous material - special handling required',
    documents: [
      'Transport Document',
      'Phytosanitary Certificate',
      'Commercial Invoice',
      'Timber Grading Certificate',
      'Kiln Dry Certificate',
      'Chain of Custody Certificate',
      'ISPM 15 Heat Treatment Certificate',
      'Dangerous Goods Declaration',
      'CITES Permit'
    ],
    relatedPOs: []
  },
  {
    id: '11',
    supplierName: 'Japanese Precision Parts',
    poNumber: 'PO-2025-011',
    port: 'Tokyo Airport',
    dateClear: '2025-07-08',
    type: 'Air',
    poType: 'Multiple',
    term: 'EXW',
    permitStatus: true,
    blAwbNumber: 'AWB-999888777',
    qualityContainer: 'QC-A011',
    taxStatus: true,
    etd: '2025-07-05',
    eta: '2025-07-07',
    status: 'in-transit',
    progress: 65,
    pstStatus: 'completed',
    supplierContact: '+81-3-1234-5678',
    supplierEmail: 'export@japanprecision.co.jp',
    supplierAddress: '1-2-3 Industrial District, Tokyo, Japan',
    totalValue: 189000,
    weight: '850 kg',
    dimensions: '80x60x50 cm',
    assignedAgent: 'Hiroshi Tanaka',
    agentContact: '+1-555-0234',
    trackingNumber: 'JP999888777',
    customsDeclaration: 'CD-2025-0189',
    insurance: true,
    priority: 'High',
    specialInstructions: 'Precision instruments - shock sensitive',
    documents: [
      'Air Waybill',
      'Commercial Invoice',
      'Technical Specifications',
      'Calibration Certificate',
      'ISO 9001 Certificate',
      'Precision Measurement Report',
      'Material Certificates',
      'Handling Instructions',
      'Temperature Control Certificate',
      'Anti-Vibration Packaging Certificate'
    ],
    relatedPOs: []
  },
  {
    id: '12',
    supplierName: 'Australian Mining Equipment',
    poNumber: 'PO-2025-012',
    port: 'Melbourne Port',
    dateClear: '2025-07-26',
    type: 'Oversea',
    poType: 'Single',
    term: 'CIF',
    permitStatus: false,
    blAwbNumber: 'BL-123987456',
    qualityContainer: 'CONT-345678',
    taxStatus: true,
    etd: '2025-07-14',
    eta: '2025-07-23',
    status: 'preparing',
    progress: 15,
    pstStatus: 'not-started',
    supplierContact: '+61-3-9876-5432',
    supplierEmail: 'shipping@ausmine.com.au',
    supplierAddress: '456 Mining Road, Melbourne, VIC, Australia',
    totalValue: 445000,
    weight: '35,600 kg',
    dimensions: '40ft Container + Open Top',
    assignedAgent: 'Emma Thompson',
    agentContact: '+1-555-0567',
    trackingNumber: 'AM123987456',
    customsDeclaration: 'CD-2025-0201',
    insurance: true,
    priority: 'High',
    specialInstructions: 'Heavy machinery - special crane required',
    documents: [
      'Bill of Lading',
      'Commercial Invoice',
      'Technical Manual',
      'Safety Certificate',
      'Heavy Equipment Certificate',
      'Crane Lifting Instructions',
      'Machinery Compliance Certificate',
      'Export Control Classification',
      'Dangerous Goods Declaration',
      'Installation Guidelines'
    ],
    relatedPOs: []
  },
  {
    id: '13',
    supplierName: 'Korean Electronics Ltd',
    poNumber: 'PO-2025-013',
    port: 'Busan Port',
    dateClear: '2025-07-21',
    type: 'Air',
    poType: 'Co-load',
    term: 'FOB',
    permitStatus: true,
    blAwbNumber: 'AWB-654321987',
    qualityContainer: 'QC-A013',
    taxStatus: true,
    etd: '2025-07-18',
    eta: '2025-07-20',
    status: 'preparing',
    progress: 80,
    pstStatus: 'in-progress',
    supplierContact: '+82-51-1234-5678',
    supplierEmail: 'exports@koreanelectronics.kr',
    supplierAddress: '789 Tech Valley, Busan, South Korea',
    totalValue: 167500,
    weight: '1,890 kg',
    dimensions: '150x90x70 cm',
    assignedAgent: 'Kim Min-jung',
    agentContact: '+1-555-0890',
    trackingNumber: 'KE654321987',
    customsDeclaration: 'CD-2025-0223',
    insurance: true,
    priority: 'Medium',
    specialInstructions: 'Electronics - ESD protection required',
    documents: [
      'Air Waybill',
      'Commercial Invoice',
      'CE Certificate',
      'Packing List',
      'K-Mark Certificate',
      'EMC Test Report',
      'Safety Compliance Certificate',
      'ESD Protection Certificate',
      'Lithium Battery Declaration',
      'Export License Korea'
    ],
    relatedPOs: ['PO-2025-019', 'PO-2025-020']
  },
  {
    id: '14',
    supplierName: 'Mexican Automotive Parts',
    poNumber: 'PO-2025-014',
    port: 'Tijuana Border',
    dateClear: '2025-07-07',
    type: 'Truck',
    poType: 'Multiple',
    term: 'DDP',
    permitStatus: true,
    blAwbNumber: 'TR-789456123',
    qualityContainer: 'QC-T014',
    taxStatus: false,
    etd: '2025-07-04',
    eta: '2025-07-05',
    status: 'completed',
    progress: 100,
    pstStatus: 'completed',
    supplierContact: '+52-664-123-4567',
    supplierEmail: 'logistics@mexautoparts.mx',
    supplierAddress: 'Zona Industrial, Tijuana, BC, Mexico',
    totalValue: 78900,
    weight: '5,600 kg',
    dimensions: 'Truck Load',
    assignedAgent: 'Diego Martinez',
    agentContact: '+1-555-0123',
    trackingNumber: 'MA789456123',
    customsDeclaration: 'CD-2025-0245',
    insurance: false,
    priority: 'Low',
    specialInstructions: 'Automotive parts - oil resistant packaging',
    documents: [
      'Transport Document',
      'Commercial Invoice',
      'NAFTA Certificate',
      'Packing List',
      'Automotive Parts Certificate',
      'IATF 16949 Certificate',
      'Material Safety Data Sheet',
      'Part Number Cross Reference',
      'Border Crossing Permit'
    ],
    relatedPOs: []
  },
  {
    id: '15',
    supplierName: 'Italian Fashion House',
    poNumber: 'PO-2025-015',
    port: 'Milan Airport',
    dateClear: '2025-07-19',
    type: 'Air',
    poType: 'Single',
    term: 'EXW',
    permitStatus: true,
    blAwbNumber: 'AWB-147258369',
    qualityContainer: 'QC-A015',
    taxStatus: true,
    etd: '2025-07-15',
    eta: '2025-07-18',
    status: 'preparing',
    progress: 75,
    pstStatus: 'in-progress',
    supplierContact: '+39-02-1234-5678',
    supplierEmail: 'export@italianfashion.it',
    supplierAddress: 'Via Moda 123, Milan, Italy',
    totalValue: 125000,
    weight: '680 kg',
    dimensions: '120x80x40 cm',
    assignedAgent: 'Francesca Rossi',
    agentContact: '+1-555-0456',
    trackingNumber: 'IF147258369',
    customsDeclaration: 'CD-2025-0267',
    insurance: true,
    priority: 'High',
    specialInstructions: 'Luxury goods - premium handling',
    documents: [
      'Air Waybill',
      'Commercial Invoice',
      'Brand Certificate',
      'Insurance Policy',
      'Authenticity Certificate',
      'Made in Italy Certificate',
      'Luxury Goods Declaration',
      'Fashion Industry Certificate',
      'Designer Authorization',
      'High Value Goods Declaration'
    ],
    relatedPOs: []
  },
  {
    id: '16',
    supplierName: 'Turkish Carpets & Rugs',
    poNumber: 'PO-2025-016',
    port: 'Istanbul Port',
    dateClear: '2025-07-12',
    type: 'Oversea',
    poType: 'Single',
    term: 'CFR',
    permitStatus: true,
    blAwbNumber: 'BL-369258147',
    qualityContainer: 'CONT-456789',
    taxStatus: true,
    etd: '2025-06-29',
    eta: '2025-07-10',
    status: 'delayed',
    progress: 45,
    pstStatus: 'in-progress',
    supplierContact: '+90-212-345-6789',
    supplierEmail: 'exports@turkishcarpets.com.tr',
    supplierAddress: 'Grand Bazaar District, Istanbul, Turkey',
    totalValue: 89600,
    weight: '8,900 kg',
    dimensions: '20ft Container',
    assignedAgent: 'Ayşe Demir',
    agentContact: '+1-555-0789',
    trackingNumber: 'TC369258147',
    customsDeclaration: 'CD-2025-0289',
    insurance: false,
    priority: 'Medium',
    specialInstructions: 'Handmade carpets - careful handling required',
    documents: [
      'Bill of Lading',
      'Commercial Invoice',
      'Certificate of Origin',
      'Quality Certificate',
      'Handmade Carpet Certificate',
      'Cultural Heritage Certificate',
      'Artisan Certification',
      'Traditional Craft Certificate',
      'Wool Quality Certificate'
    ],
    relatedPOs: []
  },
  {
    id: '17',
    supplierName: 'African Minerals Trading',
    poNumber: 'PO-2025-017',
    port: 'Cape Town Port',
    dateClear: '2025-07-18',
    type: 'Oversea',
    poType: 'Co-load',
    term: 'FOB',
    permitStatus: false,
    blAwbNumber: 'BL-852963741',
    qualityContainer: 'CONT-567890',
    taxStatus: true,
    etd: '2025-07-01',
    eta: '2025-07-15',
    status: 'submitted',
    progress: 20,
    pstStatus: 'not-started',
    supplierContact: '+27-21-123-4567',
    supplierEmail: 'shipping@africanminerals.co.za',
    supplierAddress: 'Mining District, Cape Town, South Africa',
    totalValue: 356000,
    weight: '45,000 kg',
    dimensions: '40ft Container',
    assignedAgent: 'Nelson Mandela Jr.',
    agentContact: '+1-555-0234',
    trackingNumber: 'AM852963741',
    customsDeclaration: 'CD-2025-0301',
    insurance: true,
    priority: 'High',
    specialInstructions: 'Raw materials - dust protection required',
    documents: [
      'Bill of Lading',
      'Commercial Invoice',
      'Mining Certificate',
      'Export Permit',
      'Mineral Analysis Report',
      'Kimberley Process Certificate',
      'Environmental Compliance Certificate',
      'Conflict-Free Minerals Declaration',
      'Radiation Safety Certificate',
      'Dust Protection Certificate'
    ],
    relatedPOs: ['PO-2025-021', 'PO-2025-022']
  },
  {
    id: '18',
    supplierName: 'Russian Steel Works',
    poNumber: 'PO-2025-018',
    port: 'St. Petersburg Port',
    dateClear: '2025-07-14',
    type: 'Oversea',
    poType: 'Multiple',
    term: 'CIF',
    permitStatus: true,
    blAwbNumber: 'BL-741852963',
    qualityContainer: 'CONT-678901',
    taxStatus: true,
    etd: '2025-06-27',
    eta: '2025-07-11',
    status: 'clearance',
    progress: 90,
    pstStatus: 'completed',
    supplierContact: '+7-812-123-4567',
    supplierEmail: 'export@russiansteel.ru',
    supplierAddress: 'Industrial Zone, St. Petersburg, Russia',
    totalValue: 267000,
    weight: '52,000 kg',
    dimensions: '40ft Container',
    assignedAgent: 'Vladimir Petrov',
    agentContact: '+1-555-0567',
    trackingNumber: 'RS741852963',
    customsDeclaration: 'CD-2025-0323',
    insurance: true,
    priority: 'Medium',
    specialInstructions: 'Steel products - corrosion protection applied',
    documents: [
      'Bill of Lading',
      'Commercial Invoice',
      'Steel Certificate',
      'Quality Report',
      'Mill Test Certificate',
      'Chemical Composition Report',
      'Mechanical Properties Report',
      'Corrosion Protection Certificate',
      'GOST Certificate',
      'Export Control License'
    ],
    relatedPOs: []
  },
  {
    id: '19',
    supplierName: 'Chilean Wine Exporters',
    poNumber: 'PO-2025-019',
    port: 'Valparaiso Port',
    dateClear: '2025-07-11',
    type: 'Oversea',
    poType: 'Single',
    term: 'FOB',
    permitStatus: true,
    blAwbNumber: 'BL-159753486',
    qualityContainer: 'CONT-789012',
    taxStatus: false,
    etd: '2025-06-26',
    eta: '2025-07-08',
    status: 'completed',
    progress: 100,
    pstStatus: 'completed',
    supplierContact: '+56-32-234-5678',
    supplierEmail: 'exports@chileanwine.cl',
    supplierAddress: 'Valle Central, Valparaiso, Chile',
    totalValue: 134500,
    weight: '18,600 kg',
    dimensions: '20ft Reefer Container',
    assignedAgent: 'Maria Gonzalez',
    agentContact: '+1-555-0890',
    trackingNumber: 'CW159753486',
    customsDeclaration: 'CD-2025-0345',
    insurance: true,
    priority: 'Medium',
    specialInstructions: 'Wine - temperature controlled transport',
    documents: [
      'Bill of Lading',
      'Commercial Invoice',
      'Wine Certificate',
      'Temperature Log',
      'Alcohol Content Certificate',
      'Vineyard Certificate',
      'Organic Wine Certificate',
      'Sulfite Declaration',
      'Health Certificate',
      'Export Wine License'
    ],
    relatedPOs: []
  },
  {
    id: '20',
    supplierName: 'Thai Electronics Assembly',
    poNumber: 'PO-2025-020',
    port: 'Bangkok Airport',
    dateClear: '2025-07-06',
    type: 'Air',
    poType: 'Multiple',
    term: 'DDP',
    permitStatus: true,
    blAwbNumber: 'AWB-486159753',
    qualityContainer: 'QC-A020',
    taxStatus: true,
    etd: '2025-07-03',
    eta: '2025-07-05',
    status: 'completed',
    progress: 100,
    pstStatus: 'completed',
    supplierContact: '+66-2-345-6789',
    supplierEmail: 'logistics@thaielectronics.co.th',
    supplierAddress: 'Industrial Estate, Bangkok, Thailand',
    totalValue: 95700,
    weight: '1,450 kg',
    dimensions: '110x70x50 cm',
    assignedAgent: 'Siriporn Nakamura',
    agentContact: '+1-555-0123',
    trackingNumber: 'TE486159753',
    customsDeclaration: 'CD-2025-0367',
    insurance: false,
    priority: 'Low',
    specialInstructions: 'Electronic components - anti-static required',
    documents: [
      'Air Waybill',
      'Commercial Invoice',
      'Component List',
      'Quality Report',
      'Assembly Instructions',
      'Thailand Export License',
      'Electronic Component Certificate',
      'Anti-Static Certificate',
      'RoHS Compliance Certificate'
    ],
    relatedPOs: []
  },
  {
    id: '21',
    supplierName: 'Vietnamese Textiles Co.',
    poNumber: 'PO-2025-021',
    port: 'Ho Chi Minh Port',
    dateClear: '2025-07-13',
    type: 'Oversea',
    poType: 'Co-load',
    term: 'FOB',
    permitStatus: true,
    blAwbNumber: 'BL-753159486',
    qualityContainer: 'CONT-890123',
    taxStatus: true,
    etd: '2025-07-02',
    eta: '2025-07-10',
    status: 'in-transit',
    progress: 68,
    pstStatus: 'completed',
    supplierContact: '+84-28-123-4567',
    supplierEmail: 'export@vietnamtextiles.vn',
    supplierAddress: 'Textile District, Ho Chi Minh City, Vietnam',
    totalValue: 76300,
    weight: '11,200 kg',
    dimensions: '40ft Container',
    assignedAgent: 'Nguyen Thi Lan',
    agentContact: '+1-555-0456',
    trackingNumber: 'VT753159486',
    customsDeclaration: 'CD-2025-0389',
    insurance: true,
    priority: 'Medium',
    specialInstructions: 'Garments - humidity protection required',
    documents: [
      'Bill of Lading',
      'Commercial Invoice',
      'Textile Certificate',
      'Packing List',
      'Better Cotton Initiative Certificate',
      'Social Compliance Certificate',
      'Care Label Instructions',
      'Fabric Testing Report',
      'Vietnam Export License'
    ],
    relatedPOs: ['PO-2025-023', 'PO-2025-024']
  },
  {
    id: '22',
    supplierName: 'Egyptian Cotton Mills',
    poNumber: 'PO-2025-022',
    port: 'Alexandria Port',
    dateClear: '2025-07-17',
    type: 'Oversea',
    poType: 'Single',
    term: 'CIF',
    permitStatus: true,
    blAwbNumber: 'BL-486753159',
    qualityContainer: 'CONT-901234',
    taxStatus: false,
    etd: '2025-07-04',
    eta: '2025-07-14',
    status: 'delayed',
    progress: 30,
    pstStatus: 'not-started',
    supplierContact: '+20-3-456-7890',
    supplierEmail: 'exports@egyptcotton.com.eg',
    supplierAddress: 'Cotton District, Alexandria, Egypt',
    totalValue: 112000,
    weight: '15,800 kg',
    dimensions: '40ft Container',
    assignedAgent: 'Ahmed Hassan',
    agentContact: '+1-555-0789',
    trackingNumber: 'EC486753159',
    customsDeclaration: 'CD-2025-0401',
    insurance: true,
    priority: 'High',
    specialInstructions: 'Premium cotton - moisture control critical',
    documents: [
      'Bill of Lading',
      'Commercial Invoice',
      'Cotton Certificate',
      'Quality Report',
      'Egyptian Cotton Certificate',
      'Fiber Length Certificate',
      'Organic Cotton Certificate',
      'Moisture Content Report',
      'Staple Length Report',
      'Export Cotton License'
    ],
    relatedPOs: []
  },
  {
    id: '23',
    supplierName: 'Moroccan Handicrafts',
    poNumber: 'PO-2025-023',
    port: 'Casablanca Port',
    dateClear: '2025-07-25',
    type: 'Air',
    poType: 'Single',
    term: 'EXW',
    permitStatus: true,
    blAwbNumber: 'AWB-159486753',
    qualityContainer: 'QC-A023',
    taxStatus: true,
    etd: '2025-07-14',
    eta: '2025-07-19',
    status: 'preparing',
    progress: 10,
    pstStatus: 'not-started',
    supplierContact: '+212-522-234-567',
    supplierEmail: 'export@moroccancraft.ma',
    supplierAddress: 'Medina District, Casablanca, Morocco',
    totalValue: 45600,
    weight: '890 kg',
    dimensions: '90x60x40 cm',
    assignedAgent: 'Fatima Al-Zahra',
    agentContact: '+1-555-0234',
    trackingNumber: 'MH159486753',
    customsDeclaration: 'CD-2025-0423',
    insurance: false,
    priority: 'Low',
    specialInstructions: 'Handcrafted items - fragile handling',
    documents: [
      'Air Waybill',
      'Commercial Invoice',
      'Handicraft Certificate',
      'Cultural Export Permit',
      'Artisan Certificate',
      'Traditional Craft Certificate',
      'Morocco Export License',
      'Authenticity Certificate',
      'Heritage Craft Certificate'
    ],
    relatedPOs: []
  }
];

// Mock data for notifications
const mockNotifications = [
  {
    id: "n1",
    type: "mention" as const,
    title: "You were mentioned in PO-2025-001",
    message:
      "Sarah Chen: @Mike Rodriguez please verify the refrigeration unit.",
    poNumber: "PO-2025-001",
    author: "Sarah Chen",
    timestamp: "2025-07-04T10:30:00Z",
    isRead: false,
    priority: "medium" as const,
    actionRequired: true,
  },
  {
    id: "n2",
    type: "comment" as const,
    title: "New comment on PO-2025-002",
    message:
      "Jennifer Kim: Documentation review completed. Tax clearance pending.",
    poNumber: "PO-2025-002",
    author: "Jennifer Kim",
    timestamp: "2025-07-04T09:00:00Z",
    isRead: false,
    priority: "high" as const,
    actionRequired: true,
  },
  {
    id: "n3",
    type: "system" as const,
    title: "Shipment status updated",
    message: "PO-2025-001 status changed to In Transit",
    poNumber: "PO-2025-001",
    timestamp: "2025-07-04T12:00:00Z",
    isRead: true,
    priority: "low" as const,
  },
  {
    id: "n4",
    type: "action" as const,
    title: "Urgent: Permit expiring soon",
    message: "PO-2025-004 permit expires in 2 days. Renewal required.",
    poNumber: "PO-2025-004",
    timestamp: "2025-07-04T08:00:00Z",
    isRead: false,
    priority: "high" as const,
    actionRequired: true,
  },
  {
    id: "n5",
    type: "update" as const,
    title: "Delivery completed",
    message: "PO-2025-003 has been successfully delivered.",
    poNumber: "PO-2025-003",
    timestamp: "2025-07-03T15:30:00Z",
    isRead: true,
    priority: "low" as const,
  },
];

export default function Dashboard() {
  const [notifications, setNotifications] = useState(mockNotifications);
  const [isNotificationOpen, setIsNotificationOpen] = useState(false);
    const [selectedShipment, setSelectedShipment] = useState<unknown>(null);
  const [isPanelOpen, setIsPanelOpen] = useState(false);
  const [activeTab, setActiveTab] = useState<"details" | "communication">("details");
  const unreadNotificationCount = notifications.filter((n) => !n.isRead).length;
  const handleMarkNotificationAsRead = (id: string) => {
    setNotifications((prev) =>
      prev.map((n) => (n.id === id ? { ...n, isRead: true } : n))
    );
  };

  const handleMarkAllNotificationsAsRead = () => {
    setNotifications((prev) => prev.map((n) => ({ ...n, isRead: true })));
  };

  const handleDeleteNotification = (id: string) => {
    setNotifications((prev) => prev.filter((n) => n.id !== id));
  };

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const handleNotificationClick = (notification: any) => {
    const shipment = mockShipments.find(
      (s) => s.poNumber === notification.poNumber
    );
    if (shipment) {
      setSelectedShipment(shipment);
      setActiveTab("communication");
      setIsPanelOpen(true);
      setIsNotificationOpen(false);
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 p-6">
      <div className="max-w-7xl mx-auto space-y-6">
        <div className="flex items-center justify-between">
          <div className="space-y-1">
            <h1 className="text-3xl font-bold text-gray-900 tracking-tight">
              Shipping Management Dashboard
            </h1>
            <div className="flex items-center gap-4">
              <p className="text-gray-600">
                Track and manage your logistics operations
              </p>
              <div className="flex items-center gap-2 px-3 py-1 bg-green-50 border border-green-200 rounded-full">
                <div className="w-2 h-2 bg-green-500 rounded-full animate-pulse"></div>
                <span className="text-sm font-medium text-green-700">
                  All Systems Operational
                </span>
              </div>
            </div>
          </div>
          <div className="flex items-center gap-4">
            {/* Notification Bell */}
            <Popover
              open={isNotificationOpen}
              onOpenChange={setIsNotificationOpen}
            >
              <PopoverTrigger asChild>
                <Button variant="outline" size="sm" className="relative">
                  <Bell className="w-4 h-4" />
                  {unreadNotificationCount > 0 && (
                    <Badge className="absolute -top-2 -right-2 w-5 h-5 flex items-center justify-center p-0 text-xs">
                      {unreadNotificationCount > 9
                        ? "9+"
                        : unreadNotificationCount}
                    </Badge>
                  )}
                </Button>
              </PopoverTrigger>
              <PopoverContent className="w-96 p-0" align="end">
                <NotificationCenter
                  notifications={notifications}
                  onMarkAsRead={handleMarkNotificationAsRead}
                  onMarkAllAsRead={handleMarkAllNotificationsAsRead}
                  onDeleteNotification={handleDeleteNotification}
                  onNotificationClick={handleNotificationClick}
                />
              </PopoverContent>
            </Popover>

            <div className="flex items-center gap-2 px-3 py-2 bg-gray-50 rounded-lg border">
              <Calendar className="w-4 h-4 text-gray-500" />
              <span className="text-sm font-medium text-gray-700">
                Monday, July 14, 2025
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
